In [11]:
import plotly.express as px
import plotly 
import pandas as pd
import matplotlib
import numpy as np
import scipy.stats

In [4]:
data = np.random.rand(5)


In [6]:
data

array([0.85778643, 0.92299838, 0.93551215, 0.94070324, 0.57155046])

In [8]:
data2 = np.random.rand(5)
data3= np.random.rand(5)
data4=np.random.rand(5)
data5=np.random.rand(5)


In [9]:
data
data2
data3
data4
data5

array([0.31683056, 0.18513491, 0.38493829, 0.11099854, 0.47545415])

In [17]:
import scipy.stats as stats


# Perform an independent t-test
t_statistic, p_value = stats.ttest_ind(data, data2)

# Output the results
print("T-statistic:", t_statistic)
print("P-value:", p_value)

# Determine if the difference is statistically significant
alpha = 0.05  # Significance level
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between the groups.")
else:
    print("Fail to reject the null hypothesis: There is no significant difference between the groups.")


T-statistic: 1.3881942210785956
P-value: 0.20251082092417613
Fail to reject the null hypothesis: There is no significant difference between the groups.


In [15]:
data

array([0.85778643, 0.92299838, 0.93551215, 0.94070324, 0.57155046])

In [14]:
data2

array([0.19834086, 0.67380619, 0.99264789, 0.90569194, 0.13249912])

In [18]:
test1=[10,20,30,40,50]
test2=[1,2,3,4,5]

In [19]:
import scipy.stats as stats


# Perform an independent t-test
t_statistic, p_value = stats.ttest_ind(test1, test2)

# Output the results
print("T-statistic:", t_statistic)
print("P-value:", p_value)

# Determine if the difference is statistically significant
alpha = 0.05  # Significance level
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between the groups.")
else:
    print("Fail to reject the null hypothesis: There is no significant difference between the groups.")


T-statistic: 3.7994267415435763
P-value: 0.005240940516978861
Reject the null hypothesis: There is a significant difference between the groups.
